config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/events/show/:city/:region/:id' => "events#show"

  get "/search" => "search#index"

  get '/search/show/:city/:region/:id/:date' => "search#show"

  resource :sessions, only: [:create, :destroy]
  

    resources :users
    resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
   has_and_belongs_to_many :users
end

app/models/events_user.rb
class EventsUser < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
   has_and_belongs_to_many :events
   has_secure_password 

   validates :user_name, uniqueness: true

   validates :password_confirmation, presence: true

   has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" },
      default_url: "/images/thumb/missing.png"
      validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
    unless current_user.present?
      redirect_to '/'
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
	  	current_date = Date.today.to_s
	  	
	  	@ip = request.remote_ip
      @events = HTTParty.get("http://api.bandsintown.com/events/search?date=#{current_date}&location=#{@ip}&radius=&format=json&app_id=YOUR_APP_ID
  ")
	  	

	end

  def show
  	current_date = Date.today.to_s
  	event_id = params[:id]
  	city = params[:city]
  	region = params[:region]
    @ip = request.remote_ip
  	@single
  	@all_events = HTTParty.get("http://api.bandsintown.com/events/search?date=#{current_date}&location=#{@ip}&radius=&format=json&app_id=YOUR_APP_ID")		
  	@all_events.each do |event|
  		if event['id'] == event_id.to_i
  			@single = event
  		end
  	end
    date = @single['datetime'].gsub!("T", " ")
    @the_date = DateTime.parse(date).strftime('%A %B %d, %I:%M %p %Y')
    event_search = Event.where({venue_name: @single['venue']['name'], date: @single['datetime']})
    
    if event_search.length > 0
      @see_users = event_search.map do |event|
        event.users
      end
    else 
      @see_users = []
    end
    
 		@event=Event.new
  end


  def create
    search = EventsUser.where(user_id: params["event"]["user_id"])
    gather = search.map do |s|
      double = Event.find_by(id: s["event_id"])
      double
    end
    duplicate = false

    gather.each do |s|
    if s["venue_name"] == params["event"]["venue_name"] && s["artist_name"] == params["event"]["artist_name"]
      duplicate = true
      end
    end
    if duplicate == true
      redirect_to events_path
    else      
    	event = Event.create(event_params)
    	EventsUser.create({event_id: event.id, user_id: session[:user_id]})
    	redirect_to events_path
    end
  end

  def destroy
  	event =Event.find(params[:id])
  	event_user = EventsUser.find_by({event_id: params[:id]})
  	if event_user['user_id'] == session[:user_id]
  		event.destroy
  		redirect_to '/users/' + session[:user_id].to_s

  	else 
  		flash[:error] = "You do not have access"
		redirect_to '/users/' + session[:user_id].to_s
		end
	end


  private
  def event_params
  	params.require(:event).permit(:artist_name, :artist_image, :venue_name, :location, :date, :lat, :long)
end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	
	def index
		@date = params["date"]
	  	@ip = request.remote_ip
      @events = HTTParty.get("http://api.bandsintown.com/events/search?date=#{@date}&location=#{@ip}&radius=&format=json&app_id=YOUR_APP_ID
  ")
  

	end


  def show
		date = params[:date]  	
		event_id = params[:id]
  	city = params[:city]
  	region = params[:region]
    @ip = request.remote_ip
  	@single
  	@all_events = HTTParty.get("http://api.bandsintown.com/events/search?date=#{date}&location=#{@ip}&radius=&format=json&app_id=YOUR_APP_ID")		
  	@all_events.each do |event|
  		if event['id'] == event_id.to_i

  			@single = event
  		end
  	end
    date = @single['datetime'].gsub!("T", " ")
    @the_date = DateTime.parse(date).strftime('%A %B %d, %I:%M %p %Y')

    event_search = Event.where({venue_name: @single['venue']['name'], date: @single['datetime']})
    
    if event_search.length > 0
      @see_users = event_search.map do |event|
      event.users
      end
    else 
      @see_users = []
    end

 		@event=Event.new
  end


  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.find_by({user_name: params[:user_name]})  #unique username is better
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to events_path
    else
      flash[:error] = "Incorrect user Name or Password"
      redirect_to '/'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController

before_action :authenticate, except: [:new, :create]

	def index
		@users =User.all
	end

	def new
		@user =User.new
	end

	def create
		@user = User.create(user_params)
		if @user.save
		 session[:user_id] = @user.id
		 redirect_to events_path
		else
		 flash[:error] = "There was error creating your profile"
		 render template: "welcome/index"
		end
	end

	def show
		@user = User.find(params[:id])
		@user_events = @user.events
		if session[:user_id] != @user.id
			@show_buttons = false
		else 
			@show_buttons = true
		end
		
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attribute(:user_name, params["user"]["user_name"])
		@user.update_attribute(:about_me, params["user"]["about_me"])
		@user.update_attribute(:twitter, params["user"]["twitter"])
		@user.update_attribute(:avatar, params["user"]["avatar"])
		redirect_to user_path(@user)

		# if @user.update_attributes(user_params)
		# 	 #if update succeeeds, redirect to user path
		# 	 redirect_to user_path(@user)

		# else
		# 		#if update fails, redirect to edit form
		# 	render('edit')
		# end

	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		session[:user_id] = nil
		redirect_to "/"

	end

	private
	def user_params
		params.require(:user).permit(:user_name, :password, :password_confirmation, :about_me, :twitter, :avatar)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if session[:user_id] != nil
		redirect_to "/events"
	end
    @user = User.new


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_maps.html.erb
<script type="text/javascript">
      
      
      var map;

      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat:parseFloat($.cookie("lat")), lng:parseFloat($.cookie("long"))},
          zoom: 12,
        });

        
     <% @events.each do | event | %>
      var marker = new google.maps.Marker({
         position: {lat:<%=event['venue']['latitude']%>, lng:<%=event['venue']['longitude']%>},
         map: map,
         title: '<%=event['venue']['name']%>'

       });
          
          google.maps.event.addListener(marker, 'click', function() {
      window.location.href = "/events/show/<%=event['venue']['city']%>/<%=event['venue']['region']%>/<%=event['id']%>";
      });
      <%end%>

      }


</script>

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  
  </head>

  <body>
	 <div class="wrapper">
    <div id="map"></div>

    <div class="event-list">
      
      <h1 id="center">Events Happening Nearby</h1>
        <% counter=0%>
        <% @events.each do |event| %>
       
          <div class = "event-wrapper">
            binding.pry
          	 <a href="/events/show/<%=event['venue']['city']%>/<%=event['venue']['region']%>/<%=event['id']%>">
          <% date = event['datetime'].gsub!("T", " ")
          the_date = DateTime.parse(date).strftime('%A %B %d, %I:%M %p %Y') %>
          <h4><%=event['venue']['name']%> , <%=event['venue']['region']%></h4> 
          <h5><%= the_date%></h5>
          <ul class="inline-list">
          <li>Performing:</li>
          <%event['artists'].each do |artist| %>
          <li><em><%=artist['name']%> </em> </li>
          <%end%>
          </ul>
        </a>
        </div>
        <% counter += 1%>
      <%end%>

    </div><!--event-list-->

<%= render 'maps'%>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_ID']%>&callback=initMap">
</script>
  </div>
  </body>
</html>

app/views/events/show.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      html, body { height: 100%; margin: 0; padding: 0; }
      #map { height: 275px; width:450px;}
    </style>
  </head>

  <body id="usershow">
<div id="user-show-background"> <img src="http://wallpaper.pickywallpapers.com/1920x1080/concert.jpg" alt=""></div><!--user-show_background-->
<div class="headercontainer">
	<div id="show-header">
	 <div id="map"></div>
	 <div id="event-info">
		<h2><%=@single['venue']['name']%></h2>
		<h3><%=@single['venue']['city']%>, <%=@single['venue']['region']%></h3>
		<h4><%=@the_date%></h4>
		</div>
	</div>
</div>
<script type="text/javascript">

    var map;

    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat:40.73, lng:-73.99},
        zoom: 12
      });


    var marker = new google.maps.Marker({
			 position: {lat:<%=@single['venue']['latitude']%>, lng:<%=@single['venue']['longitude']%>},
		   map: map,
		   title: '<%=@single['venue']['name']%>'

		 });
        
   
    }

</script>

</div>

<div id="artists-show">

<h4>Artists Performing:</h4>
	<%@single['artists'].each do |artist| %>
	<h6><%=artist['name']%></h6>
		<div id="spotify-image-container">
	<% if artist['name'].delete(" ").match(/^[A-z]+$/) %>

		<% response = HTTParty.get("https://api.spotify.com/v1/search?q="+artist['name']+"&type=artist") %>
			<% filtered = response["artists"]["items"].select do |e| %>
				<%if e["images"] != [ ]%>
					<% e["images"][0]["url"] %>
					<%end%>
				<% end %>
				<% if filtered == [] %>
					<img src="https://collettejellisdesign.files.wordpress.com/2013/08/mwcharacters-silhouette-png.png?w=1020">
				<% elsif filtered %>
					<img src=<%= filtered[0]["images"][1]["url"] %>>
				<% end %>
	<% else %>
		<img src="https://collettejellisdesign.files.wordpress.com/2013/08/mwcharacters-silhouette-png.png?w=1020">

	<%end%>
				</div>
			<%end%>
			</ul>
	<div id="center">		
<a class="tiny button" href="<%=@single['ticket_url']%>" target="_blank">Buy Tickets</a>

<%= form_for @event do |f| %>

 <%=f.hidden_field  :venue_name, value: @single['venue']['name'] %>
 <%=f.hidden_field :user_id, value: session[:user_id]%> 
 <%=f.hidden_field :artist_name, value: @single['artists'][0]['name']%> 
 <%=f.hidden_field :location, value: @single['venue']['city']%>
 <%=f.hidden_field :date, value: @the_date%>
 <%=f.hidden_field :lat, value: @single['venue']['latitude']%>
 <%=f.hidden_field :long, value: @single['venue']['longitude']%>
 <%=f.submit 'Save Event', class: 'tiny success button' %>

<%end%>
</div>
</div>
<div id="other-users">
<h4>Other users who saved this event:</h4>
<% @see_users.each do |user|%>
<div id="other-avatars">
  <a href="/users/<%= user[0].id%>"> <%= image_tag user[0].avatar.url(:thumb) %></a>
</div>
<% end %>
</div>


<script async defer
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_ID']%>&callback=initMap">
</script>


 </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventer</title>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One|Oswald:400,300' rel='stylesheet' type='text/css'>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<nav class="top-bar navigate" data-topbar role="navigation">
  <ul class="title-area">
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
     <!-- <li class="title"><a href="#"><span>Home</span></a></li> -->

  <li class="name">
      <a href="/events"><img src= <%=image_path("eventr_logo.png")%> /></a>
  </li>
  </ul>


  <section class="top-bar-section">

    <ul class="center-buttons">
      
      <li class="has-form">
        <li class="has-form">
          
          <form action="/search" method="GET" class="row">
            <div class="large-8 small-9 columns">
              <input type="date" name="date" id="search_bar" class="radius">
            </div>
            <div id="search_bar" class="large-4 small-3 columns">
              <button class="success button radius">Search</button>
            </div>
          </form>

        </li>
        </div>
      </li>
      
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      
      <% if session[:user_id]%>
      <li> <%= link_to "Logout", sessions_path, method: :delete %> </li>
      <li> <a href="/users/<%= session[:user_id]%>">Saved Events</a> </li>
      <% end %>
    </ul>

    <!-- Left Nav Section -->
    <!-- <ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul> -->

  </section>
</nav>

<%= yield %>

</body>
</html>

app/views/search/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  
  </head>

  <body>
  	<div class="wrapper">
    <div id="map"></div>
    
    <script type="text/javascript">

	    var map;

	    function initMap() {
	      map = new google.maps.Map(document.getElementById('map'), {
	        center: {lat:parseFloat($.cookie("lat")), lng:parseFloat($.cookie("long"))},
	        zoom: 12
	      });

	   <% @events.each do | event | %>
	    var marker = new google.maps.Marker({
  			 position: {lat:<%=event['venue']['latitude']%>, lng:<%=event['venue']['longitude']%>},
			   map: map,
			   title: '<%=event['venue']['name']%>'
			
			 });
	     google.maps.event.addListener(marker, 'click', function() {
    	window.location.href = "/search/show/<%=event['venue']['city']%>/<%=event['venue']['region']%>/<%=event['id']%>/<%=@date%>";
			});
			<%end%>

	    }

	  </script>

	  <div class="event-list">
			<h1>Events on <%=@date%></h1>
				<% @events.each do |event| %>
				<a href="/search/show/<%=event['venue']['city']%>/<%=event['venue']['region']%>/<%=event['id']%>/<%=@date%>">
				<div class="event-wrapper">
				<% date = event['datetime'].gsub!("T", " ")
    		the_date = DateTime.parse(date).strftime('%A %B %d, %I:%M %p %Y') %>
				<h4><%=event['venue']['name']%> <%=event['venue']['region']%></h4> 
				<h5><%=the_date%></h5>
				<ul class="inline-list">
					<li>Performing: </li>

					<%event['artists'].each do |artist| %>
					<li><em><%=artist['name']%></em></li>
					<%end%>
				</ul>
				</li>
			</div></a>
			<%end%>

	  </div><!--event-list-->


    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_ID']%>&callback=initMap">
    </script>
  </div>
  </body>
</html>

app/views/search/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      html, body { height: 100%; margin: 0; padding: 0; }
      #map { height: 275px; width:450px;}
    </style>
  </head>

  <body id="usershow">
	<div id="user-show-background"> <img src="http://wallpaper.pickywallpapers.com/1920x1080/concert.jpg" alt=""></div><!--user-show_background-->
	<div class="headercontainer">
	<div id="show-header">
 	<div id="map"></div>
 	 <div id="event-info">
	<h2><%=@single['venue']['name']%></h2>
	<h3><%=@single['venue']['city']%>, <%=@single['venue']['region']%></h3>
	<h4><%=@the_date%></h4>
	</div>
	</div>

	<script type="text/javascript">

    var map;

    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat:parseFloat($.cookie("lat")), lng:parseFloat($.cookie("long"))},
        zoom: 12
      });


    var marker = new google.maps.Marker({
			 position: {lat:<%=@single['venue']['latitude']%>, lng:<%=@single['venue']['longitude']%>},
		   map: map,
		   title: '<%=@single['venue']['name']%>'

		 });
        google.maps.event.addListener(marker, 'click', function() {
	window.location.href = this.url;
		});
   
    }

</script>
</div>
<div id="artists-show">
<h6>Artists Performing:</h6>
	<%@single['artists'].each do |artist| %>
	<h6><%=artist['name']%></h6>
		<div id="spotify-image-container">
		<% if artist['name'].delete(" ").match(/^[A-z]+$/) %>

		<% response = HTTParty.get("https://api.spotify.com/v1/search?q="+artist['name']+"&type=artist") %>
			<% filtered = response["artists"]["items"].select do |e| %>
				<%if e["images"] != [ ]%>
					<% e["images"][0]["url"] %>
					<%end%>
				<% end %>
				<% if filtered == [] %>
					<img src="https://collettejellisdesign.files.wordpress.com/2013/08/mwcharacters-silhouette-png.png?w=1020">
				<% elsif filtered %>
					<img src=<%= filtered[0]["images"][1]["url"] %>>
				<% end %>
	<% else %>
		<img src="https://collettejellisdesign.files.wordpress.com/2013/08/mwcharacters-silhouette-png.png?w=1020">

	<%end%>
				</div>
			<%end%>
			</ul>
		<div id="center">
	<a class="tiny button" href="<%=@single['ticket_url']%>" target="_blank">Buy Tickets</a>

 <%= form_for @event do |f| %>

<%=f.hidden_field  :venue_name, value: @single['venue']['name'] %>
<%=f.hidden_field :user_id, value: session[:user_id]%> 
<%=f.hidden_field :artist_name, value: @single['artists'][0]['name']%> 
<%=f.hidden_field :location, value: @single['venue']['city']%>
<%=f.hidden_field :date, value: @single['datetime']%>
<%=f.submit 'Save Event', class: "tiny success button"%>

<%end%>
</div>
</div>
<div id="other-users">
<h4>Other users who saved this event:</h4>
<% @see_users.each do |user|%>
<div id="other-avatars">
  <a href="/users/<%= user[0].id%>"> <%= image_tag user[0].avatar.url(:thumb) %></a>
</div>
<% end %>
</div>

<script async defer
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_ID']%>&callback=initMap">
</script>
 </body>
</html>

app/views/users/_map.html.erb
<script type="text/javascript">
      

      var map;

      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat:parseFloat($.cookie("lat")), lng:parseFloat($.cookie("long"))},
          zoom: 12,
        });

        <% counter=0%>
     <% @user_events.each do | event | %>
      var marker = new google.maps.Marker({
         position: {lat:<%=event['lat']%>, lng:<%=event['long']%>},
         map: map,
         title: '<%=event['venue_name']%>'

       });
      <%end%>

      }


</script>

app/views/users/edit.html.erb
<div class="userinfo">

<%= form_for @user, html: {multipart: true} do |f| %>
    Update username:
    <%= f.text_field :user_name, placeholder: 'username' %><br>
    Update 'About Me':
    <%= f.text_field :about_me, placeholder: 'about me'%><br>
    Update Twitter:
    <%=f.text_field :twitter, placeholder: 'twitter' %>  
    <%= f.file_field :avatar, placeholder: 'medium' %> 
    <%= f.submit %>

<% end %>

<div><!--userinfo-->

app/views/users/index.html.erb
<h1>List of all users</h1>
<% @users.each do |user| %>
	<ul>
		<li>username: <%=user.user_name%></li>
		<li>twitter: <%=user.twitter%></li>
    <li> <img src="<%= user.avatar%>" style="height:50px; width:50px"> </li>
    <li>About me: <%= user.about_me%></li>
</ul>
<%end%>

app/views/users/new.html.erb
<!-- prolly don't need a new user page cuz we add user via login/sign-in page -->

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
  
  </head>

<body id="usershow">

<div id="user-show-background"> <img src="http://wallpaper.pickywallpapers.com/1920x1080/concert.jpg" alt=""></div><!--user-show_background-->

<div class="headercontainer">

  <div class="row" id="user-info">
    <div class="small-3 columns" id="avatar">
        
      <div class="avatar">
        <h1 id="username_show"><%= @user.user_name %></h1>
        <%= image_tag @user.avatar.url(:medium) %>
      </div><!--avatar-->
      <div class="user-show-buttons">
        <%if @show_buttons == true %>

          <%= button_to "Edit Profile", edit_user_path, method: :get, class: 'tiny secondary  button' %>


          <%=button_to 'Delete Profile', user_path(@user), :method => :delete, :data => {:confirm => "are you sure?"}, class: 'tiny alert button' %>
         <%end%>
      </div><!--buttons-->

    </div><!--small-3 columns-->
    <div class="small-9 columns text">
      <h3>Username:</h3>
      <%= @user.user_name %>
      <h3>Twitter: </h3>  
      <a href='https://www.twitter.com/<%=@user.twitter%>'>@<%= @user.twitter %></a>
      <h3> About <%= @user.user_name %> </h3> 
      <%=@user.about_me%> 
    </div><!--small-9 columns-->
  </div><!--headerbox-->
</div><!--headercontainer-->

<div class="events-container">
  <div class="user-events-header">
    <h1><%= @user.user_name %>'s Events</h1>
  </div>
    <ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-4">
      <% @user_events.each do |event|%>
        <li>
          <div class="events">
            <% the_date = event.date.strftime('%A %B %d, %I:%M %p %Y') %>
            <span class="venue_name"><%=event.venue_name%></span> <%=event.location%><br>
            <span class="artist_name"><%=event.artist_name%></span> <br> <%=the_date%>
              <%=button_to "Delete event", '/events/'+event.id.to_s, method: :delete, class: 'tiny alert button' %>
          </div><!--events-->
        </li>
      <%end%>
     </br>
    </ul><!--small-block-grid-2 medium-block-grid-3 large-block-grid-4-->

  </div><!--events-container-->


</body>
</html>

app/views/welcome/index.html.erb
<div class="back"> <img src="http://wallpaper.pickywallpapers.com/1920x1080/concert.jpg" alt=""> </div>

<p style="color:red"> <strong><%= flash[:error]%></strong> </p>

<ul class="accordion" data-accordion>
  <li class="accordion-navigation">
    <a href="#panel1a">Login</a>
    <div id="panel1a" class="content active">
      <%= form_tag(sessions_path) do %>
        <%= text_field_tag :user_name, nil, placeholder: "Enter Username"%> <br>
        <%= password_field_tag :password, nil, placeholder: "Password"%>
        <%= button_tag "Login", class:"success radius"%>
      <% end %>
    </div>
  </li>
  <li class="accordion-navigation">
    <a href="#panel2a">Sign Up</a>
    <div id="panel2a" class="content">
      <% if @user.errors.any? %>
        <div id="error-explanation">
          <p><%= pluralize(@user.errors.count, "error")%> prohibited this user from being saved:</p>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li style="color: red"><%= message %></li>
          <% end %>
        </ul>
        </div>
        <% end %>
        <%= form_for @user, html: { multipart: true } do |f| %>
            
            Enter Username:
            <%= f.text_field :user_name, placeholder: 'username' %>

            Twitter handle:  
            <%= f.text_field :twitter, placeholder: 'Twitter (optional)'%>  
            Enter Password


            <%= f.password_field :password, placeholder: 'Password' %></br>

            Confirm Password
            <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation' %>

            Tell us about yourself:
            <%= f.text_area :about_me, size: "30x6" %>

            Upload profile photo here:
            <%= f.label :avatar%>
            <%= f.file_field :avatar, placeholder: "thumb" %>

            <%= f.button "create", class:"radius success button" %>

        <% end %>

    </div>
  </li>
</ul>










<script>
  navigator.geolocation.getCurrentPosition(function(position){
    $.cookie("lat", position.coords.latitude)
    $.cookie("long", position.coords.longitude)
  })
  $(document).foundation({
    accordion: {
      callback : function (accordion) {
        console.log(accordion);
      }
    }
  });
</script>